name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: fake-news
  PYTHON_VERSION: '3.11'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          pip install gunicorn

      - name: Verify Azure Web App exists
        run: |
          echo "Verifying Web App existence..."
          echo "Web App Name: ${{ env.AZURE_WEBAPP_NAME }}"
          echo "Current directory contents:"
          ls -la
          echo "Backend directory contents:"
          ls -la backend/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PACKAGE_PATH }}

      - name: 'Post Deployment Status'
        if: always()
        run: |
          if [ "${{ steps.deploy-to-webapp.outcome }}" == "success" ]; then
            echo "Deployment successful!"
            echo "You can visit your app at https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          else
            echo "Deployment failed. Please check the logs above for more details."
            echo "Make sure the Web App '${{ env.AZURE_WEBAPP_NAME }}' exists in your Azure subscription."
          fi 