# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - fake-news

env:
  AZURE_WEBAPP_NAME: fake-news
  PYTHON_VERSION: '3.11'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          pip install gunicorn

      - name: Zip artifact for deployment
        run: zip release.zip ./backend/* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
          package: .

      - name: 'Post Deployment Status'
        if: always()
        run: |
          if [ "${{ steps.deploy-to-webapp.outcome }}" == "success" ]; then
            echo "Deployment successful!"
            echo "You can visit your app at https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          else
            echo "Deployment failed. Please check the logs above for more details."
            echo "Make sure the Web App '${{ env.AZURE_WEBAPP_NAME }}' exists in your Azure subscription."
          fi 